### ISSUE TITLE
Add OBC

### ISSUE THREAD

**Issue by yarikoptic** [datalad/ohbm-booth#1]
damn thing has no logo but we have various documents etc to share!
https://open-brain-consent.readthedocs.io/

**Comment by bpoldrack** [comment]
With no logo or a widely known name I'd just add to resources.

**Comment by yarikoptic** [comment]
I think we came up with an interim logo with a family guest kid. I will see into adding it to the OBC and here

**Comment by yarikoptic** [comment]
PDF though is trickier, not sure if I finish to perfection today but I will upload some crude version. https://github.com/con/open-brain-consent/pull/68

**Comment by yarikoptic** [comment]
added pdf and put it on the table ;-)
