### ISSUE TITLE
Screens to fill ...

### ISSUE THREAD

**Issue by bpoldrack** [datalad/ohbm-booth#3]
As agreed on in chat, I've (not uploaded yet) new overlays for the top row screens:
- static datalad, con, repronim in the center
- added LED "Datasets: 240TB" to the right
- static neurodebian/BIDS for the left and
- filled the left most big screen for posters, etc.

However, the left and right sections in the top row have nothing on the outermost screens yet. Need some ideas for that.

ping @yarikoptic

**Comment by yarikoptic** [comment]
See #2

**Comment by yarikoptic** [comment]
all are occupied!
