### ISSUE TITLE
Booth info card

### ISSUE THREAD

**Issue by bpoldrack** [datalad/ohbm-booth#5]
Looking through the exhibit hall, there's two things:
- The mouse over of our booth only reads "Center for Open Neuroscience" twice (as in title + description).
- the exhibit hall comes with a "Choose an exhibitor" Button listing all booths. We show up with no logo and "Center for Open Neuroscience"

So, prob. needs some tuning, if people are supposed to find us looking for DataLad, ReproNim, BIDS, Neurodebian.

**Comment by bpoldrack** [comment]
Actually, those are different things. What's shown there is not what's called info card. It's accessible via settings of the room. Changed description to

```
- Center for Open Neuroscience
- DataLad
- ReproNim
- BIDS
- Neurodebian
```

for now. Looking for where to assign a logo ...

**Comment by bpoldrack** [comment]
Seems this requires a "Booth Logo" being added to the actual booth. Which is a shame, since this would double all the things we already have in there. We would need to make sure it's hidden in the actual booth, but exists. That way it would show up only in the "Choose an exhibitor" list.

**Comment by bpoldrack** [comment]
Any idea how we can change the title of the booth to something that's more "inclusive" to all the things it is about, @yarikoptic?

**Comment by yarikoptic** [comment]
CON: DataLad, ReproNim, BIDS, et al
?

**Comment by yarikoptic** [comment]
I filled out some information with CON: DataLad, ReproNim, BIDS, et al as the title

**Comment by bpoldrack** [comment]
I have copied that over to room title/description, so it will show up in the exhibition hall, too. (mouse-over and exhibitor list)
